### ISSUE TITLE
No module named 'nsgp'

### ISSUE THREAD

**Issue by tiantian0612** [patel-zeel/AAAI22#4]
Thanks for your kind work

I'm running you code at “nonstat_gp_cat”.However，when running lib.py, it was found that the nsgp package could not be found.
error info :
        Traceback (most recent call last):
  File "D:/毕设/AAAI22-main/nonstat_gp_cat/lib.py", line 16, in <module>
    from nsgp.utils.inducing_functions import f_kmeans, f_random
ModuleNotFoundError: No module named 'nsgp'

![QQ截图20230228195052](https://user-images.githubusercontent.com/106005883/221846506-846db93b-919d-4d1e-aa07-3d51a7034c1d.png)

I would appreciate it if you could tell me how to solve this problem！Thank you！

**Comment by tiantian0612** [comment]
@patel-zeel @shivam15s @Harshp1802

**Comment by tiantian0612** [comment]
@patel-zeel

**Comment by patel-zeel** [comment]
This should be resolved after `pip install git+https://github.com/patel-zeel/nsgp-torch`. Please feel free to reopen the issue if it does not solve the problem.
